# Generated by Django 6.0.3 on 2026-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_created_at_todo_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("in progress", "In Progress"),
                    ("discontinued", "Discontinued"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
